apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terraform-registry

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: terraform-registry
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

images:
  - name: ghcr.io/veritas-calculus/vc-terraform-registry-backend
    newTag: latest
  - name: ghcr.io/veritas-calculus/vc-terraform-registry-frontend
    newTag: latest
